/* This file is automatically generated */
#ifndef CONFIG_H
#define CONFIG_H

/* #define PARANOID  */
#define PKGDATADIR "/usr/local/createswf"
#define PKGLIBDIR "/usr/local/lib"
/* #define LOCALEDIR "" */

#endif
