#############################################################################
# Makefile for building: createswf
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  createswf.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile createswf.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Isrc -Isrc/common -Isrc/constants -Isrc/gui -Isrc/parsers -Isrc/ports -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = createswf1.0.0
DISTDIR = /home/akiko/workspace/createswf.git/.obj/createswf1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Gui -lQt5Xml -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = src/CoreApplication.cpp \
		src/main.cpp \
		src/common/Compiler.cpp \
		src/common/Logger.cpp \
		src/common/MemoryAllocator.cpp \
		src/gui/AboutDialog.cpp \
		src/gui/MainWindow.cpp \
		src/gui/PreferencesDialog.cpp \
		src/parsers/AbstractAssetsParser.cpp \
		src/parsers/CommandLineParser.cpp \
		src/parsers/DefinitionParser.cpp \
		src/parsers/DirectoryParser.cpp \
		src/ports/Darwin.cpp \
		src/ports/Unix.cpp \
		src/ports/Windows.cpp .rcc/qrc_images.cpp \
		.rcc/qrc_templates.cpp \
		.moc/moc_CoreApplication.cpp \
		.moc/moc_AboutDialog.cpp \
		.moc/moc_MainWindow.cpp
OBJECTS       = .obj/CoreApplication.o \
		.obj/main.o \
		.obj/Compiler.o \
		.obj/Logger.o \
		.obj/MemoryAllocator.o \
		.obj/AboutDialog.o \
		.obj/MainWindow.o \
		.obj/PreferencesDialog.o \
		.obj/AbstractAssetsParser.o \
		.obj/CommandLineParser.o \
		.obj/DefinitionParser.o \
		.obj/DirectoryParser.o \
		.obj/Darwin.o \
		.obj/Unix.o \
		.obj/Windows.o \
		.obj/qrc_images.o \
		.obj/qrc_templates.o \
		.obj/moc_CoreApplication.o \
		.obj/moc_AboutDialog.o \
		.obj/moc_MainWindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		createswf.pro config.h \
		src/CoreApplication.h \
		src/common/Compiler.h \
		src/common/Logger.h \
		src/common/MemoryAllocator.h \
		src/common/Version.h \
		src/constants/CompileMode.h \
		src/constants/Content.h \
		src/constants/FileType.h \
		src/gui/AboutDialog.h \
		src/gui/MainWindow.h \
		src/gui/PreferencesDialog.h \
		src/parsers/AbstractAssetsParser.h \
		src/parsers/CommandLineParser.h \
		src/parsers/DefinitionParser.h \
		src/parsers/DirectoryParser.h \
		src/ports/Darwin.h \
		src/ports/ISystem.h \
		src/ports/System.h \
		src/ports/Unix.h \
		src/ports/Windows.h src/CoreApplication.cpp \
		src/main.cpp \
		src/common/Compiler.cpp \
		src/common/Logger.cpp \
		src/common/MemoryAllocator.cpp \
		src/gui/AboutDialog.cpp \
		src/gui/MainWindow.cpp \
		src/gui/PreferencesDialog.cpp \
		src/parsers/AbstractAssetsParser.cpp \
		src/parsers/CommandLineParser.cpp \
		src/parsers/DefinitionParser.cpp \
		src/parsers/DirectoryParser.cpp \
		src/ports/Darwin.cpp \
		src/ports/Unix.cpp \
		src/ports/Windows.cpp
QMAKE_TARGET  = createswf
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = createswf


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: createswf.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		createswf.pro \
		src/images/images.qrc \
		src/templates/templates.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Xml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile createswf.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
createswf.pro:
src/images/images.qrc:
src/templates/templates.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Xml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile createswf.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/images/images.qrc src/templates/templates.qrc $(DISTDIR)/
	$(COPY_FILE) --parents config.h src/CoreApplication.h src/common/Compiler.h src/common/Logger.h src/common/MemoryAllocator.h src/common/Version.h src/constants/CompileMode.h src/constants/Content.h src/constants/FileType.h src/gui/AboutDialog.h src/gui/MainWindow.h src/gui/PreferencesDialog.h src/parsers/AbstractAssetsParser.h src/parsers/CommandLineParser.h src/parsers/DefinitionParser.h src/parsers/DirectoryParser.h src/ports/Darwin.h src/ports/ISystem.h src/ports/System.h src/ports/Unix.h src/ports/Windows.h $(DISTDIR)/
	$(COPY_FILE) --parents src/CoreApplication.cpp src/main.cpp src/common/Compiler.cpp src/common/Logger.cpp src/common/MemoryAllocator.cpp src/gui/AboutDialog.cpp src/gui/MainWindow.cpp src/gui/PreferencesDialog.cpp src/parsers/AbstractAssetsParser.cpp src/parsers/CommandLineParser.cpp src/parsers/DefinitionParser.cpp src/parsers/DirectoryParser.cpp src/ports/Darwin.cpp src/ports/Unix.cpp src/ports/Windows.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/translations/app_de.ts src/translations/app_en.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: .rcc/qrc_images.cpp .rcc/qrc_templates.cpp
compiler_rcc_clean:
	-$(DEL_FILE) .rcc/qrc_images.cpp .rcc/qrc_templates.cpp
.rcc/qrc_images.cpp: src/images/images.qrc \
		src/images/256x256/logo.png \
		src/images/16x16/open.png \
		src/images/32x32/open.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name images src/images/images.qrc -o .rcc/qrc_images.cpp

.rcc/qrc_templates.cpp: src/templates/templates.qrc \
		src/templates/BitmapData.as \
		src/templates/Main.as \
		src/templates/Sound.as \
		src/templates/Sprite.as \
		src/templates/ExtendedSprite.as \
		src/templates/MovieClip.as \
		src/templates/ExtendedMovieClip.as \
		src/templates/ByteArray.as
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name templates src/templates/templates.qrc -o .rcc/qrc_templates.cpp

compiler_moc_header_make_all: .moc/moc_CoreApplication.cpp .moc/moc_AboutDialog.cpp .moc/moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_CoreApplication.cpp .moc/moc_AboutDialog.cpp .moc/moc_MainWindow.cpp
.moc/moc_CoreApplication.cpp: src/common/Compiler.h \
		src/parsers/DefinitionParser.h \
		src/parsers/AbstractAssetsParser.h \
		src/common/MemoryAllocator.h \
		src/constants/FileType.h \
		src/constants/Content.h \
		src/constants/CompileMode.h \
		src/CoreApplication.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/akiko/workspace/createswf.git -I/home/akiko/workspace/createswf.git -I/home/akiko/workspace/createswf.git/src -I/home/akiko/workspace/createswf.git/src/common -I/home/akiko/workspace/createswf.git/src/constants -I/home/akiko/workspace/createswf.git/src/gui -I/home/akiko/workspace/createswf.git/src/parsers -I/home/akiko/workspace/createswf.git/src/ports -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/CoreApplication.h -o .moc/moc_CoreApplication.cpp

.moc/moc_AboutDialog.cpp: src/gui/AboutDialog.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/akiko/workspace/createswf.git -I/home/akiko/workspace/createswf.git -I/home/akiko/workspace/createswf.git/src -I/home/akiko/workspace/createswf.git/src/common -I/home/akiko/workspace/createswf.git/src/constants -I/home/akiko/workspace/createswf.git/src/gui -I/home/akiko/workspace/createswf.git/src/parsers -I/home/akiko/workspace/createswf.git/src/ports -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/AboutDialog.h -o .moc/moc_AboutDialog.cpp

.moc/moc_MainWindow.cpp: src/parsers/DefinitionParser.h \
		src/parsers/AbstractAssetsParser.h \
		src/common/MemoryAllocator.h \
		src/constants/FileType.h \
		src/constants/Content.h \
		src/constants/CompileMode.h \
		src/gui/MainWindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/akiko/workspace/createswf.git -I/home/akiko/workspace/createswf.git -I/home/akiko/workspace/createswf.git/src -I/home/akiko/workspace/createswf.git/src/common -I/home/akiko/workspace/createswf.git/src/constants -I/home/akiko/workspace/createswf.git/src/gui -I/home/akiko/workspace/createswf.git/src/parsers -I/home/akiko/workspace/createswf.git/src/ports -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/gui/MainWindow.h -o .moc/moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

.obj/CoreApplication.o: src/CoreApplication.cpp src/CoreApplication.h \
		src/common/Compiler.h \
		src/parsers/DefinitionParser.h \
		src/parsers/AbstractAssetsParser.h \
		src/common/MemoryAllocator.h \
		src/constants/FileType.h \
		src/constants/Content.h \
		src/constants/CompileMode.h \
		src/parsers/DirectoryParser.h \
		src/ports/System.h \
		src/ports/ISystem.h \
		src/common/Logger.h \
		src/common/Version.h \
		src/ports/Windows.h \
		src/ports/Darwin.h \
		src/ports/Unix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/CoreApplication.o src/CoreApplication.cpp

.obj/main.o: src/main.cpp src/CoreApplication.h \
		src/common/Compiler.h \
		src/parsers/DefinitionParser.h \
		src/parsers/AbstractAssetsParser.h \
		src/common/MemoryAllocator.h \
		src/constants/FileType.h \
		src/constants/Content.h \
		src/constants/CompileMode.h \
		src/common/Logger.h \
		src/common/Version.h \
		src/gui/MainWindow.h \
		src/parsers/CommandLineParser.h \
		src/ports/System.h \
		src/ports/ISystem.h \
		src/ports/Windows.h \
		src/ports/Darwin.h \
		src/ports/Unix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o src/main.cpp

.obj/Compiler.o: src/common/Compiler.cpp src/common/Compiler.h \
		src/common/Logger.h \
		src/constants/Content.h \
		src/ports/System.h \
		src/ports/ISystem.h \
		src/common/Version.h \
		src/ports/Windows.h \
		src/ports/Darwin.h \
		src/ports/Unix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Compiler.o src/common/Compiler.cpp

.obj/Logger.o: src/common/Logger.cpp src/common/Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Logger.o src/common/Logger.cpp

.obj/MemoryAllocator.o: src/common/MemoryAllocator.cpp src/common/MemoryAllocator.h \
		src/ports/System.h \
		src/ports/ISystem.h \
		src/common/Logger.h \
		src/common/Version.h \
		src/ports/Windows.h \
		src/ports/Darwin.h \
		src/ports/Unix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/MemoryAllocator.o src/common/MemoryAllocator.cpp

.obj/AboutDialog.o: src/gui/AboutDialog.cpp src/gui/AboutDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/AboutDialog.o src/gui/AboutDialog.cpp

.obj/MainWindow.o: src/gui/MainWindow.cpp src/gui/MainWindow.h \
		src/parsers/DefinitionParser.h \
		src/parsers/AbstractAssetsParser.h \
		src/common/MemoryAllocator.h \
		src/constants/FileType.h \
		src/constants/Content.h \
		src/constants/CompileMode.h \
		src/gui/AboutDialog.h \
		src/gui/PreferencesDialog.h \
		src/common/Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/MainWindow.o src/gui/MainWindow.cpp

.obj/PreferencesDialog.o: src/gui/PreferencesDialog.cpp src/gui/PreferencesDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/PreferencesDialog.o src/gui/PreferencesDialog.cpp

.obj/AbstractAssetsParser.o: src/parsers/AbstractAssetsParser.cpp src/parsers/AbstractAssetsParser.h \
		src/common/MemoryAllocator.h \
		src/constants/FileType.h \
		src/constants/Content.h \
		src/common/Logger.h \
		src/common/Version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/AbstractAssetsParser.o src/parsers/AbstractAssetsParser.cpp

.obj/CommandLineParser.o: src/parsers/CommandLineParser.cpp src/parsers/CommandLineParser.h \
		src/constants/CompileMode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/CommandLineParser.o src/parsers/CommandLineParser.cpp

.obj/DefinitionParser.o: src/parsers/DefinitionParser.cpp src/parsers/DefinitionParser.h \
		src/parsers/AbstractAssetsParser.h \
		src/common/MemoryAllocator.h \
		src/constants/FileType.h \
		src/constants/Content.h \
		src/constants/CompileMode.h \
		src/common/Logger.h \
		src/constants/DefinitionNode.h \
		src/ports/System.h \
		src/ports/ISystem.h \
		src/common/Version.h \
		src/ports/Windows.h \
		src/ports/Darwin.h \
		src/ports/Unix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/DefinitionParser.o src/parsers/DefinitionParser.cpp

.obj/DirectoryParser.o: src/parsers/DirectoryParser.cpp src/parsers/DirectoryParser.h \
		src/parsers/AbstractAssetsParser.h \
		src/common/MemoryAllocator.h \
		src/constants/FileType.h \
		src/constants/Content.h \
		src/common/Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/DirectoryParser.o src/parsers/DirectoryParser.cpp

.obj/Darwin.o: src/ports/Darwin.cpp src/ports/Darwin.h \
		src/ports/Unix.h \
		src/ports/ISystem.h \
		src/common/Logger.h \
		src/common/Version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Darwin.o src/ports/Darwin.cpp

.obj/Unix.o: src/ports/Unix.cpp src/ports/Unix.h \
		src/ports/ISystem.h \
		src/common/Logger.h \
		src/common/Version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Unix.o src/ports/Unix.cpp

.obj/Windows.o: src/ports/Windows.cpp src/ports/Windows.h \
		src/ports/ISystem.h \
		src/common/Logger.h \
		src/common/Version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/Windows.o src/ports/Windows.cpp

.obj/qrc_images.o: .rcc/qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/qrc_images.o .rcc/qrc_images.cpp

.obj/qrc_templates.o: .rcc/qrc_templates.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/qrc_templates.o .rcc/qrc_templates.cpp

.obj/moc_CoreApplication.o: .moc/moc_CoreApplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_CoreApplication.o .moc/moc_CoreApplication.cpp

.obj/moc_AboutDialog.o: .moc/moc_AboutDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_AboutDialog.o .moc/moc_AboutDialog.cpp

.obj/moc_MainWindow.o: .moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_MainWindow.o .moc/moc_MainWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

